SELECT * FROM CUSTOMERS;
SELECT * FROM GOODS;
SELECT * FROM RECEIPTS;
SELECT * FROM ITEMS;

SELECT COUNT(*) FROM CUSTOMERS;
SELECT COUNT(*) FROM GOODS;
SELECT COUNT(*) FROM RECEIPTS;
SELECT COUNT(*) FROM ITEMS;